workflows:
  ios-unsigned-ipa:
    name: vipfit
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: 1. Initialiser l'arborescence iOS
        script: |
          echo "Génération des dossiers natifs iOS..."
          if [ ! -d "ios" ]; then
            flutter create . --project-name vipfit --org com.hx --platforms ios
          else
            echo "Dossier iOS déjà présent."
          fi

      - name: 2. Télécharger les dépendances
        script: |
          flutter pub get

      - name: 3. Compiler la version iOS (Forçage sans signature)
        script: |
          echo "Compilation en cours..."
          # On injecte les arguments Xcode pour détruire les exigences de Provisioning Profile
          flutter build ios --release --no-codesign --build-number=1 --build-name=1.0.0 \
            --to-binary-arguments="CODE_SIGNING_ALLOWED=NO" \
            --extra-front-end-options="--no-implicit-dynamic-reexport"

      - name: 4. Créer le fichier .ipa pour Sideloadly
        script: |
          echo "Empaquetage du Payload..."
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r -q vipfit.ipa Payload
          mv vipfit.ipa ../ipa/

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - test@example.com
        notify:
          success: true
          failure: true
