workflows:
  ios-unsigned-ipa:
    name: vipfit
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: 1. Initialiser l'arborescence iOS et injecter le contournement de signature
        script: |
          echo "Génération des dossiers natifs iOS..."
          if [ ! -d "ios" ]; then
            flutter create . --project-name vipfit --org com.hx --platforms ios
          else
            echo "Dossier iOS déjà présent."
          fi
          
          echo "Désactivation forcée du Code Signing dans le projet Xcode..."
          # Ces lignes modifient directement le fichier projet Xcode pour lui injecter les règles de non-signature
          sed -i '' 's/DEVELOPMENT_TEAM = "";/DEVELOPMENT_TEAM = "";\n\t\t\t\tCODE_SIGNING_ALLOWED = NO;\n\t\t\t\tCODE_SIGNING_REQUIRED = NO;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: 2. Télécharger les dépendances
        script: |
          flutter pub get

      - name: 1.5 Générer automatiquement l'icône de l'application
        script: |
          if [ -f "assets/app_icon.png" ]; then
            flutter pub get
            dart run flutter_launcher_icons
          fi

      - name: 3. Compiler la version iOS (Propre et validée)
        script: |
          echo "Compilation en cours..."
          # On retire tout argument inconnu, la configuration interne du projet suffit désormais
          flutter build ios --release --no-codesign

      - name: 4. Créer le fichier .ipa
        script: |
          echo "Empaquetage du Payload..."
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r -q ../ipa/vipfit.ipa Payload

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - test@example.com
        notify:
          success: true
          failure: true
